config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accesses

  get 'profile' => 'users#profile'
  post 'open' => 'gate#open', defaults: { format: :json }

  root to: 'users#profile'

  telegram_webhooks BotController
end

app/models/access.rb
class Access
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :openedWith, type: String

  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document

  # enable token authentication
  acts_as_token_authenticatable
  field :authentication_token, type: String

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  field :telegram_user_id, type: Integer
  field :phone_number, type: String

  has_many :accesses
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_access, only: [:show, :edit, :update, :destroy]

  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.all
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # GET /accesses/1/edit
  def edit
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(access_params)

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render :show, status: :created, location: @access }
      else
        format.html { render :new }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accesses/1
  # PATCH/PUT /accesses/1.json
  def update
    respond_to do |format|
      if @access.update(access_params)
        format.html { redirect_to @access, notice: 'Access was successfully updated.' }
        format.json { render :show, status: :ok, location: @access }
      else
        format.html { render :edit }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access.destroy
    respond_to do |format|
      format.html { redirect_to accesses_url, notice: 'Access was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access
      @access = Access.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def access_params
      params.require(:access).permit(:openedWith, :user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/bot_controller.rb
class BotController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::MessageContext
  # include Telegram::Bot::UpdatesController::TypedUpdate

  # IMPORTANT: enable caching in order to use contexts by adding to the environment
  # config.telegram_updates_controller.session_store = :memory_store, { size: 64.megabytes }
  # replace :memory_store with whatever store you want to use (e.g. Redis)

  def start
    respond_with :message,
                 reply_markup: {
                   keyboard: [[
                     { text: 'Invia Contatto', request_contact: true }
                   ]],
                   resize_keyboard: true,
                   one_time_keyboard: true
                 },
                 text: <<-TXT.strip_heredoc
                   Per iniziare ad usare il bot devi verificare la tua autorizzazione.
                   Premi il pulsante "Invia Contatto" per iniziare.
                 TXT
    save_context :checking_authorization
  end

  context_handler :checking_authorization do
    if valid_phone_number?
      User.find_by(phone_number: update['message']['contact']['phone_number']) do |user|
        user.update_attribute :telegram_user_id, from['id']
        respond_with :message,
                     text: 'Ottimo! Il tuo numero è autorizzato',
                     reply_markup: {
                       inline_keyboard: [
                         [
                           { text: 'Apri', callback_data: user.id.to_s }
                         ]
                       ],
                       resize_keyboard: true,
                       one_time_keyboard: false
                     }
      end
    else
      respond_with :message, text: 'Eh no! Il tuo numero non può aprire il cancello'
    end
  end

  def callback_query(user_id)
    if User.where(id: user_id).exists? &&
       User.find(user_id).telegram_user_id == from['id']
      GateOpenerJob.perform_async(user: User.find(user_id), openedWith: 'Telegram')
      answer_callback_query 'Apro...'
    else
      answer_callback_query 'Ooops! Forse questo numero non è autorizzato?', show_alert: true
    end
  end

  def action_missing(action, *_args)
    if command?
      respond_with :message, text: "Non so cosa sia #{action}"
    else
      respond_with :message, text: "#{action}? Non so cosa fare"
    end
  end

  private

  def valid_phone_number?
    return false unless update['message']['contact']
    phone_number = update['message']['contact']['phone_number']
    User.where(phone_number: phone_number).exists?
  end
end

app/controllers/gate_controller.rb
class GateController < ApplicationController
  # see https://github.com/gonzalo-bulnes/simple_token_authentication#allow-controllers-to-handle-token-authentication
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  acts_as_token_authentication_handler_for User, fallback: :exception

  def open
    # render json: { ok: true }
    # Access.create(user: current_user, openedWith: params[:opened_with])
    GateOpenerJob.perform_async(user: current_user, openedWith: params[:opened_with])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
    render 'show'
  end

end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accesses/_form.html.erb
<%= form_for(access) do |f| %>
  <% if access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :openedWith %>
    <%= f.text_field :openedWith %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<h1>Editing Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Show', @access %> |
<%= link_to 'Back', accesses_path %>

app/views/accesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accesses</h1>

<table>
  <thead>
    <tr>
      <th>Openedwith</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accesses.each do |access| %>
      <tr>
        <td><%= access.openedWith %></td>
        <td><%= access.user %></td>
        <td><%= link_to 'Show', access %></td>
        <td><%= link_to 'Edit', edit_access_path(access) %></td>
        <td><%= link_to 'Destroy', access, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access', new_access_path %>

app/views/accesses/new.html.erb
<h1>New Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Back', accesses_path %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Openedwith:</strong>
  <%= @access.openedWith %>
</p>

<p>
  <strong>User:</strong>
  <%= @access.user %>
</p>

<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoldthedoorRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if user_signed_in? %>
        Welcome <%=  current_user.email %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path%> or <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<h2>IFTTT Applet configuration</h2>

<p><strong>IF:</strong> DO Button (Press a button)</p>
<p><strong>THEN:</strong> Maker (Make a web request)</p>

<p>
  <strong>Web request parameters:</strong>
  <ul>
    <li>URL: <%= open_url %></li>
    <li>Method: POST</li>
    <li>Content Type: application/json</li>
    <li>Body: <pre>{"user_email":"<%= @user.email %>","user_token":"<%= @user.authentication_token %>","openedWith":"Do Button"}</pre></li>
  </ul>
</p>